//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppResturantDemoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderdeatil
    {
        public int OredrDetailId { get; set; }
        public int OredrId { get; set; }
        public int ItemId { get; set; }
        public decimal UnitePrice { get; set; }
        public decimal Quantity { get; set; }
        public decimal Discount { get; set; }
        public decimal Total { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
